# Site settings
title: Medellin | Salar de Uyuni
email: anm898989@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://andrew-max.com" # the base hostname & protocol for your site
github_username: andrew-max
cdn_url: https://dmw492fxu64ad.cloudfront.net
# Build settings
markdown: kramdown
permalink: pretty

# Assets configuration
exclude:
  - _raw
  - .asset-cache
  - vendor
  - .gitignore

gems:
- jekyll-sitemap
